name: "Teste de Action"
on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    teste-action-jobs:
        permissions:
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        name: Execução de Custom Action
        steps:
            - name: Adicionando Comentário
              id: comment_step
              uses: thiagomsarrais/action-docker@main
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                issue-id: ${{ github.event.issue.number }}
                comment: "Teste de comentário"
                GITHUB_REPOSITORY: ${{ github.repository }}
            - name: Mostrar o id do comentário
              run: |
                echo 'Id do comentário: ${{ steps.comment_step.outputs.comment-id }}'